education/desktop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import signin, signup, courses, about, blog, blog_detail,element, specified, profile, recommendationCourse, contect


app_name = 'desktop'

urlpatterns = [
    path('signin/', signin, name="signin"),
    path('signup/', signup, name="signup"),
    path('courses/', courses, name="courses"),
    path('about/', about, name="about"),
    path('blog/', blog, name="blog"),
    path('blog-details/', blog_detail, name="blog_detail"),
    path('element/', element, name="element"),
    path('specified/<str:course_id>', specified, name="specified"),
    path('profile/', profile, name="profile"),
    path('recommendation/', recommendationCourse, name="recommendationCourse"),
    path('contect/', contect, name="contect")

] 

education/education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from desktop.views import index

from django.contrib.auth import views as auth_views
from searches.views import search_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', index, name='index'), 
    path('desktop/', include('desktop.urls', namespace='desktop')),
    path('chatsystem/', include('chatsystem.urls', namespace='chatsystem')),
    path('search/', search_view, name="search_view"),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registrations/reset_password.html"),
        name='reset_password'),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registrations/reset_password_sent.html"),
          name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registrations/reset.html"),
          name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registrations/reset_password_complete.html"), 
         name="password_reset_complete"),
        
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
                                document_root=settings.MEDIA_ROOT)

education/templates/footer.html
{% load static %}

<footer>
    <div class="footer-wrappper footer-bg">
       <!-- Footer Start-->
       <div class="footer-area footer-padding">
           <div class="container">
               <div class="row justify-content-between">
                   <div class="col-xl-4 col-lg-5 col-md-4 col-sm-6">
                       <div class="single-footer-caption mb-50">
                           <div class="single-footer-caption mb-30">
                               <!-- logo -->
                               <div class="footer-logo mb-25">
                                   <a href="index.html"><img src="{% static 'assets/img/logo/logo2_footer.png' %}" alt=""></a>
                               </div>
                               <div class="footer-tittle">
                                   <div class="footer-pera">
                                       <p>The automated process starts as soon as your clothes go into the machine.</p>
                                   </div>
                               </div>
                               <!-- social -->
                               <div class="footer-social">
                                   <a href="#"><i class="fab fa-twitter"></i></a>
                                   <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                   <a href="#"><i class="fab fa-pinterest-p"></i></a>
                               </div>
                           </div>
                       </div>
                   </div>
                   <div class="col-xl-2 col-lg-4 col-md-4 col-sm-6">
                       <div class="single-footer-caption mb-50">
                           <div class="footer-tittle">
                               <h4>Support</h4>
                               <ul>
                                   <li><a href="#">Design & creatives</a></li>
                                   <li><a href="#">Telecommunication</a></li>
                                   <li><a href="#">Restaurant</a></li>
                                   <li><a href="#">Programing</a></li>
                                   <li><a href="#">Architecture</a></li>
                               </ul>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
         <!-- Footer End-->
     </div>
    </footer>

    <div id="back-top" >
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>
    
    <!-- JS here -->
    <script src="{% static '/assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static '/assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static '/assets/js/popper.min.js'%}"></script>
    <script src="{% static '/assets/js/bootstrap.min.js'%}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static  '/assets/js/jquery.slicknav.min.js'%}"></script>
    
    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static '/assets/js/owl.carousel.min.js'%}"></script>
    <script src="{% static '/assets/js/slick.min.js'%}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static '/assets/js/wow.min.js'%}"></script>
    <script src="{% static '/assets/js/animated.headline.js'%}"></script>
    <script src="{% static '/assets/js/jquery.magnific-popup.js'%}"></script>
    
    <!-- Date Picker -->
    <script src="{% static '/assets/js/gijgo.min.js'%}"></script>
    <!-- Nice-select, sticky -->
    <script src="{% static '/assets/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static '/assets/js/jquery.sticky.js'%}"></script>
    <!-- Progress -->
    <script src="{% static '/assets/js/jquery.barfiller.js'%}"></script>
    
    <!-- counter , waypoint,Hover Direction -->
    <script src="{% static '/assets/js/jquery.counterup.min.js'%}"></script>
    <script src="{% static '/assets/js/waypoints.min.js'%}"></script>
    <script src="{% static '/assets/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static '/assets/js/hover-direction-snake.min.js'%}"></script>
    
    <!-- contact js -->
    <script src="{% static '/assets/js/contact.js'%}"></script>
    <script src="{% static '/assets/js/jquery.form.js'%}"></script>
    <script src="{% static '/assets/js/jquery.validate.min.js'%}"></script>
    <script src="{% static '/assets/js/mail-script.js'%}"></script>
    <script src="{% static '/assets/js/jquery.ajaxchimp.min.js'%}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static '/assets/js/plugins.js'%}"></script>
    <script src="{% static '/assets/js/main.js'%}"></script>
    
    </body> 
    </html>

education/templates/header.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Srijan</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/progressbar_barfiller.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
    
</head>

<body>
    <!-- ? Preloader Start -->
    
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area header-transparent">
            <div class="main-header ">
                <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo">
                                    <a href="{% url 'index' %}"><img src="{% static 'assets/img/logo/logo.png' %}" alt="" style="width: 100px; height: 100px;"></a>
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10">
                                <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                    <!-- Main-menu -->
                                    <div class="main-menu d-none d-lg-block">
                                        <nav>
                                            <ul id="navigation">                                                                                          
                                                <li class="active" ><a href="{% url 'index' %}">Home</a></li>
                                                <li><a href="{% url 'desktop:courses' %}">Courses</a></li>
                                                <li><a href="{% url 'desktop:about' %}">About</a></li>
                                                <li><a href="#">Blog</a>
                                                    <ul class="submenu">
                                                        <li><a href="{% url 'desktop:blog' %}">Blog</a></li>
                                                        <li><a href="{% url 'desktop:blog_detail'% }">Blog Details</a></li>
                                                        <li><a href="{% url 'desktop:element' %}">Element</a></li>
                                                    </ul>
                                                </li>
                                                <!-- <li><a href="{% url 'desktop:recommendationCourse' %}">recommendation</a></li> -->
                                                <!-- Button -->
                                                {% if user.is_authenticated %}
                                                <li>
                                                    <div>
                                                        <form class="d-flex" action="/search/">
                                                          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search" style="height: 30px;">
                                                          <button class="btn-outline-success" style="height: 30px; margin-left: 5px; margin-bottom: 10px;" type="submit">Search</button>
                                                        </form>
                                                      </div>
                                                </li>
                                                
                                                {% if job_seeker.is_authenticated %}
                                                    <li>
                                                        
                                                        <a href="{% url 'desktop:profile' %}">
                                                            <img style="border-radius: 50%; height: 50px; width: 50px;" src="{% static 'assets/img/gallery/team1.png' %}" alt="Avatar">
                                                        </a>
                                                        
                                                    </li>
                                                {% endif %}
                                                {% else %}
                                                    <li class="button-header margin-left "><a href="#" class="btn">Join</a></li>
                                                    <li class="button-header"><a href="{% url 'desktop:signin' %}" class="btn btn3">Log in</a></li>
                                                {% endif %}
                                                </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div> 
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

education/templates/login.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> App landing</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
    <main class="login-body" data-vide-bg="{% static 'assets/img/login-bg.mp4' %}">
        <!-- Login Admin -->
        <form class="form-default" action="" method="POST">
            {% csrf_token %}

            <div class="login-form">
                <div>
                    {% for message in messages %}
                        <h5>{{message}}</h5>
                    {% endfor %}
                </div>
                <!-- logo-login -->
                <div class="logo-login">
                    <a href="{% url 'index' %}"><img src="{% static 'assets/img/logo/loder.png' %}" alt=""></a>
                </div>
                <h2>Login Here</h2>
                <div class="form-input">
                    <label for="name">Username</label>
                    <input  type="text" name="name" placeholder="username">
                </div>
                <div class="form-input">
                    <label for="name">Password</label>
                    <input type="password" name="password" placeholder="Password">
                </div>
                <div class="form-input pt-30">
                    <input type="submit" name="submit" value="login">
                </div>
                
                <!-- Forget Password -->
                <a href="{% url 'reset_password' %}" class="forget">Forget Password</a>
                <!-- Forget Password -->
                <a href="{% url 'desktop:signup' %}" class="registration">Registration</a>
            </div>
        </form>
        <!-- /end login form -->
    </main>


    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Video bg -->
    <script src="{% static './assets/js/jquery.vide.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Date Picker -->
    <script src="{% static './assets/js/gijgo.min.js' %}"></script>
    <!-- Nice-select, sticky -->
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>
    <!-- Progress -->
    <script src="{% static './assets/js/jquery.barfiller.js' %}"></script>
    
    <!-- counter , waypoint,Hover Direction -->
    <script src="{% static './assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static './assets/js/waypoints.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.countdown.min.js' %}"></script>
    <script src="{% static './assets/js/hover-direction-snake.min.js' %}"></script>

    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>
    
    </body>
</html>

education/templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

education/templates/register.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Srijan</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
    <!-- ? Preloader Start -->
    <!-- <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'assets/img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div> -->
    <!-- Preloader Start-->


<!-- Register -->

<main class="login-body" data-vide-bg="{% static 'assets/img/login-bg.mp4' %}">
    <!-- Login Admin -->
    <form class="form-default" action="" method="post">
        {% csrf_token %}
        
        <div class="login-form" style="height: 700px">
            <div>
                {% for message in messages %}
                    <h5>{{message}}</h5>
                {% endfor %}
            </div>
            <!-- logo-login -->
            <div class="logo-login">
                <a href="{% url 'index' %}"><img src="{% static 'assets/img/logo/loder.png' %}" alt=""></a>
            </div>
            <h2>Registration Here</h2>

            <div class="form-input">
                <label for="name">Full name</label>
                <input  type="text" name="username" placeholder="Full name">
            </div>
            <div class="form-input">
                <label for="name">Email Address</label>
                <input type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-input">
                <label for="name">Password</label>
                <input type="password" name="password" placeholder="Password">
            </div>
            <div class="form-input">
                <label for="name">Confirm Password</label>
                <input type="password" name="password2" placeholder="Confirm Password">
            </div>
            <div class="form-input pt-30">
                <input type="submit" name="submit" value="Registration">
            </div>
            <!-- Forget Password -->
            <a href="{% url 'desktop:signin' %}" class="registration">login</a>
        </div>
    </form>
    <!-- /end login form -->
</main>


    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Video bg -->
    <script src="{% static './assets/js/jquery.vide.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Date Picker -->
    <script src="{% static './assets/js/gijgo.min.js' %}"></script>
    <!-- Nice-select, sticky -->
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>
    <!-- Progress -->
    <script src="{% static './assets/js/jquery.barfiller.js' %}"></script>
    
    <!-- counter , waypoint,Hover Direction -->
    <script src="{% static './assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static './assets/js/waypoints.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.countdown.min.js' %}"></script>
    <script src="{% static './assets/js/hover-direction-snake.min.js' %}"></script>

    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>
    
    </body>
</html>